# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "00_core.ipynb",
         "X": "01_torchcirq.ipynb",
         "Y": "01_torchcirq.ipynb",
         "Z": "01_torchcirq.ipynb",
         "unity": "01_torchcirq.ipynb",
         "cz": "01_torchcirq.ipynb",
         "R1": "01_torchcirq.ipynb",
         "R3": "01_torchcirq.ipynb",
         "CZ": "01_torchcirq.ipynb",
         "Measurements": "01_torchcirq.ipynb",
         "Measurement_Z": "01_torchcirq.ipynb",
         "flatten_grad": "01_torchcirq.ipynb",
         "find_hessian": "01_torchcirq.ipynb",
         "find_heigenvalues": "01_torchcirq.ipynb",
         "loss_function": "01_torchcirq.ipynb",
         "batch_loss_function_sigmoid": "01_torchcirq.ipynb",
         "batch_loss_function": "01_torchcirq.ipynb",
         "Toy_Model": "01_torchcirq.ipynb",
         "General_Model": "01_torchcirq.ipynb",
         "Model_Z_measure": "01_torchcirq.ipynb",
         "make_complex": "03_complex.ipynb",
         "numpy": "03_complex.ipynb",
         "real": "03_complex.ipynb",
         "imag": "03_complex.ipynb",
         "scalar_mult": "03_complex.ipynb",
         "matmul": "03_complex.ipynb",
         "inner_prod": "03_complex.ipynb",
         "outer_prod": "03_complex.ipynb",
         "einsum": "03_complex.ipynb",
         "conjugate": "03_complex.ipynb",
         "conj": "03_complex.ipynb",
         "elementwise_mult": "03_complex.ipynb",
         "elementwise_division": "03_complex.ipynb",
         "absolute_value": "03_complex.ipynb",
         "kronecker_prod": "03_complex.ipynb",
         "sigmoid": "03_complex.ipynb",
         "scalar_divide": "03_complex.ipynb",
         "inverse": "03_complex.ipynb",
         "norm_sqr": "03_complex.ipynb",
         "norm": "03_complex.ipynb",
         "I": "03_complex.ipynb",
         "iterate_minibatches": "04_data_helper.ipynb",
         "rot_layer": "03_pennylanecirq.ipynb",
         "entangle_layer": "03_pennylanecirq.ipynb",
         "Reuploading_model": "03_pennylanecirq.ipynb",
         "Hessian": "03_pennylanecirq.ipynb",
         "generate_circle_data": "04_data_helper.ipynb"}

modules = ["core.py",
           "torchcirq.py",
           "complex.py",
           "pennylanecirq.py",
           "data_helper.py"]

doc_url = "https://PatrickHuembeli.github.io/vqc_loss_landscapes/"

git_url = "https://github.com/PatrickHuembeli/vqc_loss_landscapes/tree/master/"

def custom_doc_links(name): return None
