# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "00_core.ipynb",
         "generate_circle_data": "01_torchcirq.ipynb",
         "plot_data": "01_torchcirq.ipynb"}

modules = ["core.py",
           "torchcirq.py"]

doc_url = "https://PatrickHuembeli.github.io/vqc_loss_landscapes/"

git_url = "https://github.com/PatrickHuembeli/vqc_loss_landscapes/tree/master/"

def custom_doc_links(name): return None
