# AUTOGENERATED! DO NOT EDIT! File to edit: 04_data_helper.ipynb (unless otherwise specified).

__all__ = ['generate_circle_data', 'iterate_minibatches']

# Cell
import numpy as np

def generate_circle_data(samples, center=[0.0, 0.0], radius=np.sqrt(2 / np.pi)):
    """Generate cirle data"""
    Xvals, yvals = [], []

    for i in range(samples):
        x = 2 * (np.random.rand(2)) - 1
        y = 0
        if np.linalg.norm(x - center) < radius:
            y = 1
        Xvals.append(x)
        yvals.append(y)
    return np.array(Xvals), np.array(yvals)

def iterate_minibatches(inputs, targets, batch_size):
    """
    Function to iterate minibatches of inputs and labels
    """
    for start_idx in range(0, inputs.shape[0] - batch_size + 1, batch_size):
        idxs = slice(start_idx, start_idx + batch_size)
        yield inputs[idxs], targets[idxs]