# AUTOGENERATED! DO NOT EDIT! File to edit: 01_torchcirq.ipynb (unless otherwise specified).

__all__ = ['generate_circle_data', 'plot_data']

# Cell
import numpy as np
import os
from matplotlib import pyplot as plt

import torch
from torch.autograd import Variable
from complex import *
import qutip.qip.circuit as QCirc
import qutip as qt
from tqdm import tqdm as tqdm

# Cell
def generate_circle_data(samples, center=[0.0, 0.0], radius=np.sqrt(2 / np.pi)):
    """Generate cirle data"""
    Xvals, yvals = [], []

    for i in range(samples):
        x = 2 * (np.random.rand(2)) - 1
        y = 0
        if np.linalg.norm(x - center) < radius:
            y = 1
        Xvals.append(x)
        yvals.append(y)
    return np.array(Xvals), np.array(yvals)


def plot_data(x, y, fig=None, ax=None):
    """Plot Data with label colors"""
    if fig == None:
        fig, ax = plt.subplots(1, 1, figsize=(5, 5))
    reds = y == 0
    blues = y == 1
    ax.scatter(x[reds, 0], x[reds, 1], s=15, edgecolor="k")
    ax.scatter(x[blues, 0], x[blues, 1], s=15, edgecolor="k")
    ax.set_xlabel("$x_1$")
    ax.set_ylabel("$x_2$")